### ISSUE TITLE
cudumpobj please add information

### ISSUE THREAD

**Issue by peepo** [ArchaeaSoftware/cudahandbook#4]
Atomics folder README:

cudumpobj --dump-sass <filename>.cubin

https://github.com/ArchaeaSoftware/cudahandbook/blob/master/atomics/README.txt

but what is cudumpobj?

there are only 2 references in Google search, both from this project.

please advise further

Jonathan

**Comment by ArchaeaSoftware** [comment]
I transposed "syllables" - it's cuobjdump!
