### ISSUE TITLE
coins.pgm

### ISSUE THREAD

**Issue by peepo** [ArchaeaSoftware/cudahandbook#5]
histogram.cu links to coins.pgm illustration 15.1, but this file is in /corr

**Comment by ArchaeaSoftware** [comment]
Yes, the Histogram source code was added some time after the book was published. Here's the article that source code accompanies: http://www.informit.com/articles/article.aspx?p=2143393

I copied the file over in the repository. (Note, from a performance standpoint, the most interesting Histogram results are obtained with the --random N command line parameter.)
